name: Serverless Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Set AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Dev
        run: serverless deploy --stage dev
      
      - name: Calculate remaining time until 2 AM in Zagreb time
        id: calculate-time
        run: |
          remaining_time=$(TZ="Europe/Zagreb" date -d '00:40 tomorrow' +%s)
          current_time=$(date +%s)
          if [[ $remaining_time -lt $current_time ]]; then
            remaining_time=$((remaining_time + 24*3600))
          fi
          remaining_seconds=$((remaining_time - current_time))
          echo "::set-output name=remaining-time::$remaining_seconds"

      - name: Sleep until 2 AM in Zagreb time
        run: sleep ${{ steps.calculate-time.outputs.remaining-time }}

      - name: Remove Dev Environment
        run: serverless remove --stage dev

  deploy-production:
    if: github.ref == 'refs/heads/main'
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Set AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Production
        run: serverless deploy --stage production